[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "error"

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#00e676"

[server]
headless = true
runOnSave = true
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true
